/*
 * generated by Xtext 2.32.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalSchemaTableParser;
import xtext.services.SchemaTableGrammarAccess;

public class SchemaTableParser extends AbstractAntlrParser {

	@Inject
	private SchemaTableGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSchemaTableParser createParser(XtextTokenStream stream) {
		return new InternalSchemaTableParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Table";
	}

	public SchemaTableGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchemaTableGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
