/*
 * generated by Xtext 2.32.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.SchemaTableRuntimeModule;
import xtext.SchemaTableStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SchemaTableIdeSetup extends SchemaTableStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SchemaTableRuntimeModule(), new SchemaTableIdeModule()));
	}
	
}
