/*
 * generated by Xtext 2.32.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.schemaTable.ui.internal.SchemaTableActivator;

public class SchemaTableUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SchemaTableActivator.getInstance().getInjector("xtext.SchemaTable");
	}

}
