/*
 * generated by Xtext 2.32.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtext.schemaTable.ui.internal.SchemaTableActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SchemaTableExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SchemaTableActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SchemaTableActivator activator = SchemaTableActivator.getInstance();
		return activator != null ? activator.getInjector(SchemaTableActivator.XTEXT_SCHEMATABLE) : null;
	}

}
