/*
 * generated by Xtext 2.32.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SchemaTableUiModule extends AbstractSchemaTableUiModule {

	public SchemaTableUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
