/*
 * generated by Xtext 2.32.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SchemaTableStandaloneSetup extends SchemaTableStandaloneSetupGenerated {

	public static void doSetup() {
		new SchemaTableStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
