/*
 * generated by Xtext 2.32.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSchemaTableScopeProvider extends DelegatingScopeProvider {
}
